'use client';
import { useEffect, useState } from 'react';
export default function Admin(){const[auth,setAuth]=useState(null),[stores,setStores]=useState([]),[settings,setSettings]=useState({featuredCities:[]}),[results,setResults]=useState([]),[storeMessage,setStoreMessage]=useState(''),[citiesMessage,setCitiesMessage]=useState(''),[searching,setSearching]=useState(false);useEffect(()=>{fetch('/api/auth').then(r=>r.json()).then(d=>setAuth(d.authenticated));},[]);const load=async()=>{const[s,c]=await Promise.all([fetch('/api/stores',{cache:'no-store'}).then(r=>r.json()),fetch('/api/settings',{cache:'no-store'}).then(r=>r.json())]);setStores(Array.isArray(s)?s:[]);setSettings(c)};useEffect(()=>{if(auth)load()},[auth]);
  if(auth===null)return <main className="login">Laden …</main>;
  if(!auth)return <Login onSuccess={()=>setAuth(true)}/>;
  const search=async(event)=>{event.preventDefault();const query=String(new FormData(event.currentTarget).get('query')||'').trim();if(query.length<3)return;setSearching(true);setStoreMessage('');const response=await fetch(`/api/geocode?q=${encodeURIComponent(query)}`);const data=await response.json();const matches=Array.isArray(data)?data:[];setResults(matches);setSearching(false);if(!response.ok)setStoreMessage(data.error);else if(matches.length===0)setStoreMessage('Keine Märkte für diese Suche gefunden.')};
  const choose=(result)=>{const a=result.address||{};['name','street','postalCode','city','lat','lng','hours'].forEach(name=>{const input=document.querySelector(`#store-form [name="${name}"]`);if(input)input.value=({name:result.name||a.shop||'',street:[a.road,a.house_number].filter(Boolean).join(' '),postalCode:a.postcode||'',city:a.city||a.town||a.village||a.municipality||'',lat:result.lat,lng:result.lon,hours:result.opening_hours||result.extratags?.opening_hours||''})[name]});setResults([])};
  const saveStore=async(event)=>{event.preventDefault();const form=event.currentTarget;const response=await fetch('/api/stores',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(form)))});const data=await response.json();setStoreMessage(response.ok?'Markt gespeichert.':data.error);if(response.ok){form.reset();setStores(current=>[...current,data].sort((a,b)=>a.city.localeCompare(b.city,'de')||a.name.localeCompare(b.name,'de')))}};
  const remove=async(id)=>{if(!confirm('Diesen Markt wirklich löschen?'))return;await fetch('/api/stores',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});load()};
  const cities=[...new Set(stores.map(s=>s.city))].sort((a,b)=>a.localeCompare(b,'de'));const toggle=(city)=>setSettings(current=>({featuredCities:current.featuredCities.includes(city)?current.featuredCities.filter(c=>c!==city):[...current.featuredCities,city]}));
  const saveCities=async()=>{const response=await fetch('/api/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(settings)});setCitiesMessage(response.ok?'Kurzliste gespeichert.':'Auswahl konnte nicht gespeichert werden.')};
  return <><header><div><p className="kicker">Team Kily Map</p><h1>Marktverwaltung</h1></div><button className="secondary" onClick={async()=>{await fetch('/api/auth',{method:'DELETE'});setAuth(false)}}>Abmelden</button></header><main className="admin-grid"><section className="panel"><h2>Markt hinzufügen</h2><p className="hint">Nach Markt, Adresse oder Postleitzahl suchen und einen Treffer auswählen.</p><form className="address-search" onSubmit={search}><label>Markt oder Adresse suchen<input name="query" placeholder="z. B. Dresden oder 09427"/></label><button disabled={searching}>{searching?'Suche …':'Suchen'}</button></form><div className="search-results">{results.map((r,i)=><button key={`${r.lat}-${i}`} onClick={()=>choose(r)}>{r.display_name}</button>)}</div><form id="store-form" onSubmit={saveStore}><label>Name<input name="name" required/></label><div className="row"><label>Straße<input name="street"/></label><label>PLZ<input name="postalCode"/></label></div><label>Stadt<input name="city" required/></label><div className="row"><label>Breitengrad<input name="lat" type="number" step="any" required/></label><label>Längengrad<input name="lng" type="number" step="any" required/></label></div><label>Öffnungszeiten<input name="hours"/></label><button>Markt speichern</button></form>{storeMessage&&<p className="notice">{storeMessage}</p>}</section><div className="admin-side"><section className="panel"><h2>Städte in der Kurzliste</h2><p className="hint">Diese Städte erscheinen als Buttons über der öffentlichen Karte.</p><div className="city-options">{cities.map(city=><label className="city-option" key={city}><input type="checkbox" checked={settings.featuredCities.includes(city)} onChange={()=>toggle(city)}/><span>{city}</span></label>)}</div><button onClick={saveCities}>Auswahl speichern</button>{citiesMessage&&<p className="notice">{citiesMessage}</p>}</section><section className="panel"><div className="panel-head"><h2>Vorhandene Märkte</h2><span>{stores.length} Einträge</span></div><div className="admin-list">{stores.map(store=><article key={store.id}><div><strong>{store.name}</strong><span>{store.street}, {store.postalCode} {store.city}</span></div><button className="danger" onClick={()=>remove(store.id)}>Löschen</button></article>)}</div></section></div></main></>}
function Login({onSuccess}){const[error,setError]=useState('');return <main className="login"><p className="kicker">Interner Bereich</p><h1>Marktverwaltung</h1><p>Bitte mit dem Admin-Passwort anmelden.</p><form onSubmit={async e=>{e.preventDefault();const password=String(new FormData(e.currentTarget).get('password'));const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});if(r.ok)onSuccess();else setError('Das Passwort ist nicht korrekt.')}}><label>Passwort<input type="password" name="password" required autoFocus/></label><button>Anmelden</button></form>{error&&<p className="notice error">{error}</p>}<a href="/">← Zur Karte</a></main>}
