'use client';
import { useEffect, useMemo, useRef, useState } from 'react';

export default function MapFinder() {
  const [stores,setStores]=useState([]), [settings,setSettings]=useState({featuredCities:[]}), [query,setQuery]=useState(''), [city,setCity]=useState(''), [active,setActive]=useState('');
  const mapElement=useRef(null), mapRef=useRef(null), markers=useRef(new Map());
  const filtered=useMemo(()=>stores.filter(store=>(!city||store.city===city)&&`${store.name} ${store.city} ${store.street} ${store.postalCode}`.toLocaleLowerCase('de').includes(query.toLocaleLowerCase('de'))),[stores,city,query]);
  useEffect(()=>{Promise.all([fetch('/api/stores').then(r=>r.json()),fetch('/api/settings').then(r=>r.json())]).then(([storeData,settingsData])=>{setStores(Array.isArray(storeData)?storeData:[]);setSettings(settingsData);});},[]);
  useEffect(()=>{if(!mapElement.current||mapRef.current||!stores.length)return; let disposed=false; import('leaflet').then(L=>{if(disposed||!mapElement.current)return; const map=L.map(mapElement.current,{zoomControl:false}).setView([51.1,10.2],6); mapRef.current=map; L.control.zoom({position:'bottomright'}).addTo(map); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>-Mitwirkende'}).addTo(map); const icon=L.divIcon({className:'custom-marker',html:'<span></span>',iconSize:[34,42],iconAnchor:[17,42],popupAnchor:[0,-38]}); stores.forEach(store=>{const marker=L.marker([store.lat,store.lng],{icon}).bindPopup(`<div class="map-popup"><span>${escapeHtml(store.city)}</span><strong>${escapeHtml(store.name)}</strong><p>${escapeHtml(address(store))}</p>${store.hours?`<p class="popup-hours">● ${escapeHtml(formatHours(store.hours))}</p>`:''}</div>`,{minWidth:210}); marker.on('click',()=>setActive(store.id)); marker.addTo(map); markers.current.set(store.id,marker);}); map.fitBounds(stores.map(s=>[s.lat,s.lng]),{padding:[60,60],maxZoom:8});}); return()=>{disposed=true;mapRef.current?.remove();mapRef.current=null;markers.current.clear();};},[stores]);
  useEffect(()=>{if(!mapRef.current)return;const ids=new Set(filtered.map(s=>s.id));markers.current.forEach((marker,id)=>{if(ids.has(id))marker.addTo(mapRef.current);else marker.remove();});},[filtered]);
  const focus=(store)=>{setActive(store.id);mapRef.current?.flyTo([store.lat,store.lng],15,{duration:.8});markers.current.get(store.id)?.openPopup();document.querySelector(`[data-store="${CSS.escape(store.id)}"]`)?.scrollIntoView({behavior:'smooth',block:'nearest'});};
  const selectCity=(value)=>{setCity(value);setActive('');const selected=stores.filter(s=>!value||s.city===value);if(selected.length)mapRef.current?.fitBounds(selected.map(s=>[s.lat,s.lng]),{padding:[50,50],maxZoom:13});};
  const featured=settings.featuredCities.filter(item=>stores.some(store=>store.city===item));
  return <><header className="site-header"><a className="brand" href="https://team-kily.de">Team Kily – interaktive Supermarktkarte</a><span className="eyebrow">Orte, die uns verbinden.</span></header><main><section className="intro"><div><p className="kicker">Team Kily Marktfinder</p><h1>Finde deinen Markt.</h1><p>Entdecke ausgewählte Märkte, Adressen und Öffnungszeiten auf einen Blick.</p></div><div className="search-wrap"><label htmlFor="city-search">Stadt oder Markt suchen</label><input id="city-search" type="search" placeholder="z. B. Dresden oder 09427" value={query} onChange={e=>setQuery(e.target.value)}/></div></section><nav className="city-chips" aria-label="Ausgewählte Städte"><button className={`chip ${!city?'active':''}`} onClick={()=>selectCity('')}>Alle Märkte</button>{featured.map(item=><button key={item} className={`chip ${city===item?'active':''}`} onClick={()=>selectCity(item)}>{item}</button>)}</nav><section className="finder"><div ref={mapElement} id="map" aria-label="Interaktive Karte mit Standorten"/><aside className="results"><div className="results-head"><div><span>{filtered.length}</span> Märkte</div><button onClick={()=>filtered.length&&mapRef.current?.fitBounds(filtered.map(s=>[s.lat,s.lng]),{padding:[50,50],maxZoom:10})}>Karte zurücksetzen</button></div><div className="store-list">{filtered.map(store=><button key={store.id} data-store={store.id} className={`store-card ${active===store.id?'active':''}`} onClick={()=>focus(store)}><span className="card-top"><span className="city-label">{store.city}</span><span>↗</span></span><strong>{store.name}</strong><span>{address(store)}</span>{store.hours&&<span className="hours"><i/>{formatHours(store.hours)}</span>}</button>)}{!filtered.length&&<p className="empty">Keine Märkte für diese Suche gefunden.</p>}</div></aside></section></main><footer><a href="https://team-kily.de">Team Kily</a><span>Kartendaten © <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">OpenStreetMap-Mitwirkende</a></span></footer></>;
}
const address=(store)=>[store.street,[store.postalCode,store.city].filter(Boolean).join(' ')].filter(Boolean).join(', ');
const monthNumber={Jan:'01',Feb:'02',Mar:'03',Apr:'04',May:'05',Jun:'06',Jul:'07',Aug:'08',Sep:'09',Oct:'10',Nov:'11',Dec:'12'};
const formatHours=(value='')=>String(value)
  .replace(/(\d{4}) ([A-Z][a-z]{2}) (\d{2})-(\d{4}) ([A-Z][a-z]{2}) (\d{2}) closed/g,(_,fromYear,fromMonth,fromDay,toYear,toMonth,toDay)=>`Geschlossen: ${fromDay}.${monthNumber[fromMonth]||fromMonth}.${fromYear}–${toDay}.${monthNumber[toMonth]||toMonth}.${toYear}`)
  .replace(/\bTu\b/g,'Di').replace(/\bWe\b/g,'Mi').replace(/\bTh\b/g,'Do').replace(/\bSu\b/g,'So')
  .replace(/\bPH\b/g,'Feiertage').replace(/\b(?:off|closed)\b/gi,'geschlossen')
  .replace(/,/g,', ').replace(/\s+/g,' ').replace(/;/g,' ·')
  .replace(/\b(Mo|Di|Mi|Do|Fr|Sa|So)-(Mo|Di|Mi|Do|Fr|Sa|So)\b/g,'$1–$2')
  .replace(/(\d{2}:\d{2})-(\d{2}:\d{2})/g,'$1–$2');
const escapeHtml=(value='')=>String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]||char));
